### PR TITLE
add node 13 to prebuild

### PR DESCRIPTION
**Pull request by trew**
This PR adds node 13 as a prebuild target.

### CODE REVIEW

**Comment by shiftkey** [comment]
@trew looks like there's an issue with this new version:

```
gyp: name 'v8_enable_pointer_compression' is not defined while evaluating condition 'v8_enable_pointer_compression == 1' in binding.gyp while trying to load binding.gyp
prebuild ERR! configure error
```

**Comment by trew** [comment]
That's strange. It builds fine on my machine. It makes me think the build environment is outdated or something.

```
prebuild info build Preparing to prebuild registry-js@1.9.0 for node 13.13.0 on win32-x64 using node-gyp
prebuild http GET https://nodejs.org/download/release/v13.13.0/node-v13.13.0-headers.tar.gz
prebuild http 200 https://nodejs.org/download/release/v13.13.0/node-v13.13.0-headers.tar.gz
prebuild http GET https://nodejs.org/download/release/v13.13.0/SHASUMS256.txt
prebuild http GET https://nodejs.org/download/release/v13.13.0/win-x86/node.lib
prebuild http GET https://nodejs.org/download/release/v13.13.0/win-x64/node.lib
prebuild http 200 https://nodejs.org/download/release/v13.13.0/win-x64/node.lib
prebuild http 200 https://nodejs.org/download/release/v13.13.0/SHASUMS256.txt
prebuild http 200 https://nodejs.org/download/release/v13.13.0/win-x86/node.lib
prebuild info spawn C:\Python27\python.EXE
prebuild info spawn args [
prebuild info spawn args   'C:\\Code\\registry-js\\node_modules\\node-gyp\\gyp\\gyp_main.py',
prebuild info spawn args   'binding.gyp',
prebuild info spawn args   '-f',
prebuild info spawn args   'msvs',
prebuild info spawn args   '-G',
prebuild info spawn args   'msvs_version=2015',
prebuild info spawn args   '-I',
prebuild info spawn args   'C:\\Code\\registry-js\\build\\config.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   'C:\\Code\\registry-js\\node_modules\\node-gyp\\addon.gypi',
prebuild info spawn args   '-I',
prebuild info spawn args   'C:\\Users\\trew\\.node-gyp\\13.13.0\\include\\node\\common.gypi',
prebuild info spawn args   '-Dlibrary=shared_library',
prebuild info spawn args   '-Dvisibility=default',
prebuild info spawn args   '-Dnode_root_dir=C:\\Users\\trew\\.node-gyp\\13.13.0',
prebuild info spawn args   '-Dnode_gyp_dir=C:\\Code\\registry-js\\node_modules\\node-gyp',
prebuild info spawn args   '-Dnode_lib_file=C:\\Users\\trew\\.node-gyp\\13.13.0\\<(target_arch)\\node.lib',
prebuild info spawn args   '-Dmodule_root_dir=C:\\Code\\registry-js',
prebuild info spawn args   '-Dnode_engine=v8',
prebuild info spawn args   '--depth=.',
prebuild info spawn args   '--no-parallel',
prebuild info spawn args   '--generator-output',
prebuild info spawn args   'C:\\Code\\registry-js\\build',
prebuild info spawn args   '-Goutput_dir=.'
prebuild info spawn args ]
prebuild info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
prebuild info spawn args [
prebuild info spawn args   'build/binding.sln',
prebuild info spawn args   '/clp:Verbosity=minimal',
prebuild info spawn args   '/nologo',
prebuild info spawn args   '/p:Configuration=Release;Platform=x64'
prebuild info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  main.cc
  win_delay_load_hook.cc
     Creating library C:\Code\registry-js\build\Release\registry.lib and object C:\Code\registry-js\build\Release\registry.exp
  registry.vcxproj -> C:\Code\registry-js\build\Release\\registry.node
prebuild info build Stripping debug information from build\Release\registry.node
prebuild info build Packing build\Release\registry.node into prebuilds\registry-js-v1.9.0-node-v79-win32-x64.tar.gz
prebuild info build Prebuild written to prebuilds\registry-js-v1.9.0-node-v79-win32-x64.tar.gz
Done in 14.31s.
```

**Comment by trew** [comment]
Looks like the CI env is using node 12. This is from the beginning of the build log:

```
Installing Node.js v12.16.2 (x64)...
```

**Comment by trew** [comment]
Noticed that node 13 is end-of-life June 2020 so I don't think this is really needed.

**Pull request closed without merging**
